[project]
name = "household-budget-server"
version = "0.1.0"
description = "The restful service used to support the Household Budget web application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.3.4",
]

[tool.pytest.ini_options]
pythonpath = "src"